basePath: /api/v1
definitions:
  models.Item:
    properties:
      id:
        example: "1"
        type: string
      is_used:
        example: false
        type: boolean
      name:
        example: Test Item
        type: string
      price:
        example: 10.5
        type: number
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: A FastAPI-like API built with Go using Gin and Swagger
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: GoAPI - FastAPI Style for Go
  version: "1.0"
paths:
  /items:
    get:
      description: Devuelve una lista de todos los items
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Item'
            type: array
      summary: Obtener todos los items
      tags:
      - items
    post:
      consumes:
      - application/json
      description: Crea un nuevo item con los datos proporcionados
      parameters:
      - description: Datos del nuevo item
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/models.Item'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Item'
      summary: Crear un nuevo item
      tags:
      - items
  /items/{id}:
    get:
      description: Devuelve un item específico por su ID
      parameters:
      - description: ID del item
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Item'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtener un item por ID
      tags:
      - items
schemes:
- http
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
tags:
- description: Operaciones con items
  name: items
